# Generated by Django 3.2.8 on 2021-11-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stucu_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('search_id', models.IntegerField(db_column='search_id', primary_key=True, serialize=False)),
                ('search_phrase', models.CharField(db_column='search_phrase', max_length=255)),
            ],
            options={
                'db_table': 'searches',
                'managed': False,
            },
        ),
    ]
