from django.urls import path

from . import views

urlpatterns = [
    path("", views.login, name="login"),
    path("processing_login/", views.process_login, name="process-login"),
    path("my_profile/", views.profile_page, name="profile-page"),
    path("categories/", views.landing_page, name="landing-page"),
    path("academics/", views.academics, name="academics-page"),
    path("academics/<int:id>", views.academics_detail, name="academics-detail-page"),
    path("on_campus_housing/", views.on_campus_housing, name="on-campus-housing-page"),
    path("on_campus_housing/<int:id>", views.on_campus_housing_detail, name="on-campus-housing-detail-page"),
    path("off_campus_housing/", views.off_campus_housing, name="off-campus-housing-page"),
    #path("off_campus_housing/<str:company>", views.off_campus_housing_detail, name="off-campus-housing-detail-page"),
    path("registered_student_organizations/", views.registered_student_organizations, name="registered-student-organizations-page"),
    #path("registered_student_organizations/<str:rso>", views.rso_detail, name="registered-student-organizations-detail-page"),
    path("restaurants/", views.restaurants, name="restaurants-page"),
    path("restaurants/<int:id>", views.restaurant_detail, name="restaurant-detail-page"),
    path("school_social_media/", views.school_social_media, name="school-social-media-page"),
    path("school_social_media/<int:id>", views.ssm_detail, name="school-social-media-detail-page"),
    path("search_results/", views.search_results, name="search-results"),
    path("academics/starring/<int:id>", views.star_academic, name="star-academic"),
    path("academics/unstarring/<int:id>", views.unstar_academic, name="unstar-academic"),
    path("on_campus_housing/starring/<int:id>", views.star_on_campus_housing, name="star-on-campus-housing"),
    path("on_campus_housing/unstarring/<int:id>", views.unstar_on_campus_housing, name="unstar-on-campus-housing"),
    #path("off_campus_housing/starring/<int:id>", views.star_off_campus_housing, name="star-off-campus-housing"),
    #path("off_campus_housing/unstarring/<int:id>", views.unstar_off_campus_housing, name="unstar-off-campus-housing"),
    #path("registered_student_organizations/starring/<int:id>", views.star_registered_student_organizations, name="star-rso"),
    #path("registered_student_organizations/unstarring/<int:id>", views.unstar_registered_student_organizations, name="unstar-rso"),
    path("restaurants/starring/<int:id>", views.star_restaurant, name="star-restaurant"),
    path("restaurants/unstarring/<int:id>", views.unstar_restaurant, name="unstar-restaurant"),
    path("school_social_media/starring/<int:id>", views.star_school_social_media, name="star-ssm"),
    path("school_social_media/unstarring/<int:id>", views.unstar_school_social_media, name="unstar-ssm"),
]
